# Generated by Django 4.1.4 on 2023-01-30 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('todo_text', models.CharField(max_length=256)),
                ('todo_create', models.DateTimeField()),
                ('todo_update', models.DateTimeField()),
                ('todo_author', models.CharField(max_length=128)),
                ('todo_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
