# Generated by Django 4.1.4 on 2023-01-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
