# Generated by Django 4.1.4 on 2023-02-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_todo_todo_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
